export interface Service {
  id: string
  network: string
  category: string
  title: string
  price: number
  oldPrice?: number
  discount: number
  icon: string
}

export interface Network {
  id: string
  name: string
  icon: string
}

export const networks: Network[] = [
  { id: "all", name: "All Networks", icon: "/interconnected-networks.png" },
  { id: "instagram", name: "Instagram", icon: "/icons/instagram.jpeg" },
  { id: "tiktok", name: "TikTok", icon: "/icons/tiktok.png" },
  { id: "twitter", name: "Twitter", icon: "/icons/twitter.png" },
  { id: "youtube", name: "YouTube", icon: "/icons/youtube.png" },
  { id: "telegram", name: "Telegram", icon: "/icons/telegram.png" },
  { id: "facebook", name: "Facebook", icon: "/icons/facebook.png" },
  { id: "twitch", name: "Twitch", icon: "/icons/twitch.png" },
  { id: "spotify", name: "Spotify", icon: "/icons/spotify.png" },
  { id: "reddit", name: "Reddit", icon: "/icons/reddit.png" },
  { id: "whatsapp", name: "WhatsApp", icon: "/icons/whatsapp.png" },
  { id: "snapchat", name: "Snapchat", icon: "/icons/snapchat.svg" },
  { id: "kick", name: "Kick", icon: "/icons/kick.png",},
  { id: "discord", name: "Discord", icon: "/icons/discord.jpeg" },
  { id: "google", name: "Google", icon: "/icons/google.png" },
]

export const services: Service[] = [

  // Instagram Followers (Refill Guaranteed)
  {
    id: "2852",
    network: "instagram",
    category: "Instagram Followers (Refill Guaranteed)",
    title: "Instagram Followers [ Max 10M ] | HQ Accounts | Drop 0-5% | No Refill ⚠️ | Instant Start | Day 500K 🚀",
    price: 16.4828,
    oldPrice: 19.7794,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },
  {
    id: "2853",
    network: "instagram",
    category: "Instagram Followers (Refill Guaranteed)",
    title: "Instagram Followers [ Max 10M ] | UHQ Accounts | Drop 0-5% | 30 Days ♻️ | Instant Start | Day 500K 🚀",
    price: 18.5934,
    oldPrice: 22.3121,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },
  {
    id: "2854",
    network: "instagram",
    category: "Instagram Followers (Refill Guaranteed)",
    title: "Instagram Followers [ Max 10M ] | UHQ Accounts | Drop 0-5% | 60 Days ♻️ | Instant Start | Day 500K 🚀",
    price: 19.85,
    oldPrice: 23.82,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },
  {
    id: "2855",
    network: "instagram",
    category: "Instagram Followers (Refill Guaranteed)",
    title: "Instagram Followers [ Max 10M ] | UHQ Accounts | Drop 0-5% | 90 Days ♻️ | Instant Start | Day 500K 🚀",
    price: 20.3525,
    oldPrice: 24.423,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },
  {
    id: "2856",
    network: "instagram",
    category: "Instagram Followers (Refill Guaranteed)",
    title: "Instagram Followers [ Max 10M ] | UHQ Accounts | Drop 0-5% | 365 Days ♻️ | Instant Start | Day 500K 🚀",
    price: 22.3625,
    oldPrice: 26.835,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },

  // Instagram Likes
  {
    id: "2908",
    network: "instagram",
    category: "Instagram Likes",
    title: "Instagram Likes [ Max 1M ] | UHQ Accounts | Low Drop | No Refill ⚠️ | Fast | Day 100K 🚀",
    price: 1.0552,
    oldPrice: 1.2662,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },
  {
    id: "2909",
    network: "instagram",
    category: "Instagram Likes",
    title: "Instagram Likes [ Max 1M ] | UHQ Accounts | Low Drop | 30 Days ♻️ | Fast | Day 100K 🚀",
    price: 1.1055,
    oldPrice: 1.3266,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },
  {
    id: "2910",
    network: "instagram",
    category: "Instagram Likes",
    title: "Instagram Likes [ Max 1M ] | UHQ Accounts | Low Drop | 60 Days ♻️ | Fast | Day 100K 🚀",
    price: 1.1559,
    oldPrice: 1.3871,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },
  {
    id: "2911",
    network: "instagram",
    category: "Instagram Likes",
    title: "Instagram Likes [ Max 1M ] | UHQ Accounts | Low Drop | 90 Days ♻️ | Fast | Day 100K 🚀",
    price: 1.2062,
    oldPrice: 1.4474,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },
  {
    id: "2912",
    network: "instagram",
    category: "Instagram Likes",
    title: "Instagram Likes [ Max 1M ] | UHQ Accounts | Low Drop | 365 Days ♻️ | Fast | Day 100K 🚀",
    price: 1.2562,
    oldPrice: 1.5074,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },

  // Instagram Views
  {
    id: "2712",
    network: "instagram",
    category: "Instagram Views",
    title: "Instagram Video Views [ Max Unlimited ] | All Link | Instant Start 🚀",
    price: 0.0041,
    oldPrice: 0.0049,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },
  {
    id: "2713",
    network: "instagram",
    category: "Instagram Views",
    title: "Instagram Video Views [ Max Unlimited ] | All Link | Super Fast Speed 🚀",
    price: 0.0049,
    oldPrice: 0.0059,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },

  // Instagram Other Services
  {
    id: "2369",
    network: "instagram",
    category: "Instagram Other Services",
    title: "Instagram Story Likes | Max 100K | Day 100K",
    price: 1.4323,
    oldPrice: 1.7188,
    discount: 17,
    icon: "/icons/instagram.jpeg",
  },

  // TikTok Followers (Refill Guaranteed)
  {
    id: "2861",
    network: "tiktok",
    category: "TikTok Followers (Refill Guaranteed)",
    title: "Tiktok Followers [ Max 1M ] | UHQ Accounts | Drop 0-5% | No Refill ⚠️ | Fast | Day 200K 🚀",
    price: 6.7841,
    oldPrice: 8.1409,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2863",
    network: "tiktok",
    category: "TikTok Followers (Refill Guaranteed)",
    title: "Tiktok Followers [ Max 1M ] | UHQ Accounts | Drop 0-5% | 30 Days ♻️ | Fast | Day 200K 🚀",
    price: 7.0355,
    oldPrice: 8.4426,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2864",
    network: "tiktok",
    category: "TikTok Followers (Refill Guaranteed)",
    title: "Tiktok Followers [ Max 1M ] | UHQ Accounts | Drop 0-5% | 90 Days ♻️ | Fast | Day 200K 🚀",
    price: 7.2866,
    oldPrice: 8.7439,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2865",
    network: "tiktok",
    category: "TikTok Followers (Refill Guaranteed)",
    title: "Tiktok Followers [ Max 1M ] | UHQ Accounts | Drop 0-5% | 365 Days ♻️ | Fast | Day 200K 🚀",
    price: 7.7892,
    oldPrice: 9.347,
    discount: 17,
    icon: "/icons/tiktok.png",
  },

  // TikTok Likes
  {
    id: "2917",
    network: "tiktok",
    category: "TikTok Likes",
    title: "Tiktok Live Stream Likes [ Max 100M ] | HQ Accounts | Start: 0-5 Minutes | Day 500K 🚀",
    price: 0.0227,
    oldPrice: 0.0272,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2918",
    network: "tiktok",
    category: "TikTok Likes",
    title: "Tiktok Live Stream Likes [ Max Unlimited ] | Instant Start | Day 500K 🚀",
    price: 0.0352,
    oldPrice: 0.0422,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2866",
    network: "tiktok",
    category: "TikTok Likes",
    title: "TikTok Likes [ Max 100K ] | UHQ Accounts | Low Drop | No Refill ⚠️ | Fast | Day 100K 🚀",
    price: 0.211,
    oldPrice: 0.2532,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2867",
    network: "tiktok",
    category: "TikTok Likes",
    title: "TikTok Likes [ Max 100K ] | UHQ Accounts | Low Drop | 30 Days ♻️ | Fast | Day 100K 🚀",
    price: 0.2162,
    oldPrice: 0.2594,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2868",
    network: "tiktok",
    category: "TikTok Likes",
    title: "TikTok Likes [ Max 100K ] | UHQ Accounts | Low Drop | 60 Days ♻️ | Fast | Day 100K 🚀",
    price: 0.2212,
    oldPrice: 0.2654,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2869",
    network: "tiktok",
    category: "TikTok Likes",
    title: "TikTok Likes [ Max 100K ] | UHQ Accounts | Low Drop | 90 Days ♻️ | Fast | Day 100K 🚀",
    price: 0.2261,
    oldPrice: 0.2713,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2870",
    network: "tiktok",
    category: "TikTok Likes",
    title: "TikTok Likes [ Max 100K ] | UHQ Accounts | Low Drop | 365 Days ♻️ | Fast | Day 100K 🚀",
    price: 0.2311,
    oldPrice: 0.2773,
    discount: 17,
    icon: "/icons/tiktok.png",
  },

  // TikTok Views
  {
    id: "2871",
    network: "tiktok",
    category: "TikTok Views",
    title: "TikTok Video Views [ Max Unlimited ] | Instant Start | Day 10M | Fast 🚀",
    price: 0.0387,
    oldPrice: 0.0464,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2872",
    network: "tiktok",
    category: "TikTok Views",
    title: "TikTok Video Views [ Max Unlimited ] | Instant Start | Day 10M | Ultra fast🚀",
    price: 0.0402,
    oldPrice: 0.0482,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2873",
    network: "tiktok",
    category: "TikTok Views",
    title: "TikTok Video Views [ Max Unlimited ] | HQ | No Refill ⚠️ | Instant Start | Day 100M 🚀",
    price: 0.0402,
    oldPrice: 0.0482,
    discount: 17,
    icon: "/icons/tiktok.png",
  },

  // TikTok Shares
  {
    id: "2915",
    network: "tiktok",
    category: "TikTok Shares",
    title: "TikTok Share [ Max Unlimited ] | HQ | Non Drop | No Refill ⚠️ | Instant Start | Day 500K 🚀",
    price: 0.2261,
    oldPrice: 0.2713,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2916",
    network: "tiktok",
    category: "TikTok Shares",
    title: "TikTok Share [ Max Unlimited ] | HQ | Non Drop | 365 Days ♻️ | Instant Start | Day 500K 🚀",
    price: 0.2511,
    oldPrice: 0.3013,
    discount: 17,
    icon: "/icons/tiktok.png",
  },

  // TikTok Saves
  {
    id: "2913",
    network: "tiktok",
    category: "TikTok Saves",
    title: "TikTok Save [ Max Unlimited ] | HQ | Non Drop | No Refill ⚠️ | Instant Start | Day 500K 🚀",
    price: 0.0451,
    oldPrice: 0.0541,
    discount: 17,
    icon: "/icons/tiktok.png",
  },
  {
    id: "2914",
    network: "tiktok",
    category: "TikTok Saves",
    title: "TikTok Save [ Max Unlimited ] | HQ | Non Drop | 365 Days ♻️ | Instant Start | Day 500K 🚀",
    price: 0.0503,
    oldPrice: 0.0604,
    discount: 17,
    icon: "/icons/tiktok.png",
  },

  // Twitter Followers
  {
    id: "2682",
    network: "twitter",
    category: "Twitter Followers",
    title: "Twitter Followers [ Worldwide 🌏 ] [ Max 20K ] | HQ Accounts | No Refill ⚠️ | Instant Start | Day 20K 🚀",
    price: 4.7741,
    oldPrice: 5.7289,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2683",
    network: "twitter",
    category: "Twitter Followers",
    title: "Twitter Followers [ Worldwide 🌏 ] [ Max 40K ] | HQ Accounts | No Refill ⚠️ | Instant Start | Day 40K 🚀",
    price: 5.0253,
    oldPrice: 6.0304,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2685",
    network: "twitter",
    category: "Twitter Followers",
    title: "Twitter Followers [ Worldwide 🌏 ] [ Max 100K ] | UHQ Accounts | Low Drop | No Refill ⚠️ | Instant Start | Day 100K 🚀",
    price: 15.0758,
    oldPrice: 18.091,
    discount: 17,
    icon: "/icons/twitter.png",
  },

  // Twitter Likes
  {
    id: "2822",
    network: "twitter",
    category: "Twitter Likes",
    title: "Twitter Likes [ Worldwide 🌍 ] [ Max 1K ] | HQ Accounts | No Refill ⚠️ | Ultra Instant Start 🚀",
    price: 2.6132,
    oldPrice: 3.1358,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2823",
    network: "twitter",
    category: "Twitter Likes",
    title: "Twitter Likes [ Worldwide 🌍 ] [ Max 50K ] | HQ Accounts | No Refill ⚠️ | Ultra Instant Start 🚀",
    price: 2.8143,
    oldPrice: 3.3772,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2824",
    network: "twitter",
    category: "Twitter Likes",
    title: "Twitter Likes [ Worldwide 🌍 ] [ Max 100K ] | HQ Accounts | No Refill ⚠️ | Ultra Instant Start 🚀",
    price: 2.8393,
    oldPrice: 3.4072,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2825",
    network: "twitter",
    category: "Twitter Likes",
    title: "Twitter Likes [ Worldwide 🌍 ] [ Max 300K ] | HQ Accounts | No Refill ⚠️ | Ultra Instant Start 🚀",
    price: 2.9397,
    oldPrice: 3.5276,
    discount: 17,
    icon: "/icons/twitter.png",
  },

  // Twitter Views
  {
    id: "2686",
    network: "twitter",
    category: "Twitter Views",
    title: "Twitter Tweet - Video Views [ Max Unlimited ] | Instant | Drop 0% | No Refill ⚠️ | Day 2M 🚀🚀",
    price: 0.034,
    oldPrice: 0.0408,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2687",
    network: "twitter",
    category: "Twitter Views",
    title: "Twitter Tweet - Video Views [ Max Unlimited ] | Instant | Drop 0% | 30 Days ♻️ | Day 2M 🚀🚀",
    price: 0.0358,
    oldPrice: 0.043,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2688",
    network: "twitter",
    category: "Twitter Views",
    title: "Twitter Tweet - Video Views [ Max Unlimited ] | Instant | Drop 0% | 60 Days ♻️ | Day 2M 🚀🚀",
    price: 0.0367,
    oldPrice: 0.044,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2689",
    network: "twitter",
    category: "Twitter Views",
    title: "Twitter Tweet - Video Views [ Max Unlimited ] | Instant | Drop 0% | 90 Days ♻️ | Day 2M 🚀🚀",
    price: 0.0378,
    oldPrice: 0.0454,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2690",
    network: "twitter",
    category: "Twitter Views",
    title: "Twitter Tweet - Video Views [ Max Unlimited ] | Instant | Drop 0% | 365 Days ♻️ | Day 2M 🚀🚀",
    price: 0.0387,
    oldPrice: 0.0464,
    discount: 17,
    icon: "/icons/twitter.png",
  },

  // Twitter Reposts
  {
    id: "2691",
    network: "twitter",
    category: "Twitter Reposts",
    title: "Twitter Retweet [ Global 🌍 ] [ Max 100K ] | HQ | No Refill ⚠️ | Instant Start | Day 100K",
    price: 3.7187,
    oldPrice: 4.4624,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2692",
    network: "twitter",
    category: "Twitter Reposts",
    title: "Twitter Retweet [ Global 🌍 ] [ Max 100K ] | HQ | 30 Days ♻️ | Instant Start | Day 100K",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2693",
    network: "twitter",
    category: "Twitter Reposts",
    title: "Twitter Retweet [ Global 🌍 ] [ Max 100K ] | HQ | 60 Days ♻️ | Instant Start | Day 100K",
    price: 3.8191,
    oldPrice: 4.5829,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2694",
    network: "twitter",
    category: "Twitter Reposts",
    title: "Twitter Retweet [ Global 🌍 ] [ Max 100K ] | HQ | 90 Days ♻️ | Instant Start | Day 100K",
    price: 3.8694,
    oldPrice: 4.6433,
    discount: 17,
    icon: "/icons/twitter.png",
  },
  {
    id: "2695",
    network: "twitter",
    category: "Twitter Reposts",
    title: "Twitter Retweet [ Global 🌍 ] [ Max 100K ] | HQ | 365 Days ♻️ | Instant Start | Day 100K",
    price: 3.9198,
    oldPrice: 4.7038,
    discount: 17,
    icon: "/icons/twitter.png",
  },

  // YouTube Subscribers
  {
    id: "2373",
    network: "youtube",
    category: "YouTube Subscribers",
    title: "YouTube Subscribers [ Max 1M ] | Low Quality | No Refill | Slow",
    price: 0.4522,
    oldPrice: 0.5426,
    discount: 17,
    icon: "/icons/youtube.png",
  },
  {
    id: "2892",
    network: "youtube",
    category: "YouTube Subscribers",
    title: "YouTube Subscribers [ Max 100K ] | High Quality | 7 Days ♻️ | Instant Start | Day 2K",
    price: 20.1011,
    oldPrice: 24.1213,
    discount: 17,
    icon: "/icons/youtube.png",
  },

  // YouTube Comment Likes
  {
    id: "2516",
    network: "youtube",
    category: "YouTube Comment Likes",
    title: "YouTube Comment Likes [ Max 50K ] | Low Quality | No Refill ⚠️ | Instant Start | Day 50K",
    price: 0.6533,
    oldPrice: 0.784,
    discount: 17,
    icon: "/icons/youtube.png",
  },
  {
    id: "2519",
    network: "youtube",
    category: "YouTube Comment Likes",
    title: "YouTube Comment Reply Likes [ Max 50K ] | Low Quality | No Refill ⚠️ | Instant Start | Day 50K",
    price: 0.6533,
    oldPrice: 0.784,
    discount: 17,
    icon: "/icons/youtube.png",
  },
  {
    id: "2517",
    network: "youtube",
    category: "YouTube Comment Likes",
    title: "YouTube Comment Likes [ Max 50K ] | High Quality | 30 Days ♻️ | Instant Start | Day 50K",
    price: 0.7537,
    oldPrice: 0.9044,
    discount: 17,
    icon: "/icons/youtube.png",
  },
  {
    id: "2520",
    network: "youtube",
    category: "YouTube Comment Likes",
    title: "YouTube Comment Reply Likes [ Max 50K ] | High Quality | 30 Days ♻️ | Instant Start | Day 50K",
    price: 0.7537,
    oldPrice: 0.9044,
    discount: 17,
    icon: "/icons/youtube.png",
  },
  {
    id: "2521",
    network: "youtube",
    category: "YouTube Comment Likes",
    title: "YouTube Comment Reply Likes [ Max 50K ] | High Quality | 365 Days ♻️ | Instant Start | Day 50K",
    price: 0.8544,
    oldPrice: 1.0253,
    discount: 17,
    icon: "/icons/youtube.png",
  },

  // YouTube Likes
  {
    id: "2791",
    network: "youtube",
    category: "YouTube Likes",
    title: "Youtube Likes [ Max 10K ] | Start: 0-15 Min | No Warranty ⚠️ | Instant | Day 10K",
    price: 0.2011,
    oldPrice: 0.2413,
    discount: 17,
    icon: "/icons/youtube.png",
  },
  {
    id: "2792",
    network: "youtube",
    category: "YouTube Likes",
    title: "Youtube Likes [ Max 1M ] | Start: 0-15 Min | No Warranty ⚠️ | Instant | Day 500K",
    price: 0.2511,
    oldPrice: 0.3013,
    discount: 17,
    icon: "/icons/youtube.png",
  },
  {
    id: "2793",
    network: "youtube",
    category: "YouTube Likes",
    title: "Youtube Likes [ Max 1M ] | HQ Profiles | 30 Days ♻️ | SuperInstant | Day 500K ⚡️",
    price: 0.3015,
    oldPrice: 0.3618,
    discount: 17,
    icon: "/icons/youtube.png",
  },
  {
    id: "2794",
    network: "youtube",
    category: "YouTube Likes",
    title: "Youtube Likes [ Max 1M ] | HQ Profiles | 90 Days ♻️ | SuperInstant | Day 500K ⚡️",
    price: 0.4022,
    oldPrice: 0.4826,
    discount: 17,
    icon: "/icons/youtube.png",
  },

  // YouTube Views
  {
    id: "2893",
    network: "youtube",
    category: "YouTube Views",
    title: "YouTube Views [ Max 1M ] | Slow | 365 Days ♻️",
    price: 3.7187,
    oldPrice: 4.4624,
    discount: 17,
    icon: "/icons/youtube.png",
  },

  // Telegram Views
  {
    id: "2879",
    network: "telegram",
    category: "Telegram Views",
    title: "Telegram Post Views [ Max Unlimited ] | Last 1 Post  🚀",
    price: 0.0076,
    oldPrice: 0.0091,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2880",
    network: "telegram",
    category: "Telegram Views",
    title: "Telegram Post Views [ Max Unlimited ] | Last 5 Post  🚀",
    price: 0.0428,
    oldPrice: 0.0514,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2881",
    network: "telegram",
    category: "Telegram Views",
    title: "Telegram Post Views [ Max Unlimited ] | Last 10 Post  🚀",
    price: 0.0879,
    oldPrice: 0.1055,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2882",
    network: "telegram",
    category: "Telegram Views",
    title: "Telegram Post Views [ Max Unlimited ] | Last 15 Post  🚀",
    price: 0.1307,
    oldPrice: 0.1568,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2883",
    network: "telegram",
    category: "Telegram Views",
    title: "Telegram Post Views [ Max Unlimited ] | Last 20 Post  🚀",
    price: 0.1758,
    oldPrice: 0.211,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2884",
    network: "telegram",
    category: "Telegram Views",
    title: "Telegram Post Views [ Max Unlimited ] | Last 50 Post  🚀",
    price: 0.4321,
    oldPrice: 0.5185,
    discount: 17,
    icon: "/icons/telegram.png",
  },

  // Telegram Members
  {
    id: "2339",
    network: "telegram",
    category: "Telegram Members",
    title: "Telegram Members [ Max 10M ] | High Quality | No Refill ⚠️ | Instant Start | Day 100K 🚀",
    price: 3.0654,
    oldPrice: 3.6785,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2876",
    network: "telegram",
    category: "Telegram Members",
    title: "Telegram Members [ Max 10M ] | High Quality | Non Drop | 30 Days ♻️ | Instant Start | Day 100K 🚀",
    price: 3.1157,
    oldPrice: 3.7388,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2877",
    network: "telegram",
    category: "Telegram Members",
    title: "Telegram Members [ Max 10M ] | High Quality | Non Drop | 60 Days ♻️ | Instant Start | Day 100K 🚀",
    price: 3.1658,
    oldPrice: 3.799,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2878",
    network: "telegram",
    category: "Telegram Members",
    title: "Telegram Members [ Max 10M ] | High Quality | Non Drop | 90 Days ♻️ | Instant Start | Day 100K 🚀",
    price: 3.2161,
    oldPrice: 3.8593,
    discount: 17,
    icon: "/icons/telegram.png",
  },

  // Telegram Reactions
  {
    id: "2522",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction  [ Red heart ❤️ ] [ Max 50K ] | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2523",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction  [ Fire 🔥 ] [ Max 50K ]  | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2524",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction  [ Laugh 🤣 ] [ Max 50K ] | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2525",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [ Handshake 🤝 ] [ Max 50K ]  | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2526",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [ Lightning Bolt ⚡️ ] [ Max 50K ]  | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2527",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [ Woozy Face 🥴 ] [ Max 50K ] | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2528",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [ Neutral Face 😐] [ Max 50K ] | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2529",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [ Eyes  👀] [ Max 50K ]  | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2530",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [ Clapping Hands 👏 ] [ Max 50K ]  | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2531",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [ Loudly Crying Face 😭 ] [ Max 50K ] | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2532",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [Pile of Poo 💩 ] [ Max 50K ] | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2533",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [Moai 🗿 ] [ Max 50K ] | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2534",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [Clown Face 🤡 ] [ Max 50K ] | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },
  {
    id: "2535",
    network: "telegram",
    category: "Telegram Reactions",
    title: "Telegram Reaction [Nerd Face 🤓 ] [ Max 50K ] | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 0.0954,
    oldPrice: 0.1145,
    discount: 17,
    icon: "/icons/telegram.png",
  },

  // Facebook Followers
  {
    id: "2746",
    network: "facebook",
    category: "Facebook Followers",
    title: "Facebook Followers [ All Type ] [ Worldwide🌎 ] [ Max 1M ] | HQ Accounts | Low Drop | No Refill ⚠️ | Fast | Day 25K 🚀",
    price: 2.4875,
    oldPrice: 2.985,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2747",
    network: "facebook",
    category: "Facebook Followers",
    title: "Facebook Followers [ All Type ] [ Worldwide🌎 ] [ Max 1M ] | HQ Accounts | Low Drop | 30 Days ♻️ | Fast | Day 25K 🚀",
    price: 2.6132,
    oldPrice: 3.1358,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2748",
    network: "facebook",
    category: "Facebook Followers",
    title: "Facebook Followers [ All Type ] [ Worldwide🌎 ] [ Max 1M ] | HQ Accounts | Low Drop | 365 Days ♻️ | Fast | Day 25K 🚀",
    price: 2.7136,
    oldPrice: 3.2563,
    discount: 17,
    icon: "/icons/facebook.png",
  },

  // Facebook Likes
  {
    id: "2885",
    network: "facebook",
    category: "Facebook Likes",
    title: "Facebook Post Likes [ Max 500K ] | HQ Accounts | Low Drop | No Refill ⚠️ | Instant Start | Day 50K 🚀",
    price: 1.2062,
    oldPrice: 1.4474,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2886",
    network: "facebook",
    category: "Facebook Likes",
    title: "Facebook Post Likes [ Max 500K ] | HQ Accounts | Low Drop | 30 Days ♻️ | Instant Start | Day 50K 🚀",
    price: 1.2562,
    oldPrice: 1.5074,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2887",
    network: "facebook",
    category: "Facebook Likes",
    title: "Facebook Post Likes [ Max 500K ] | HQ Accounts | Low Drop | 60 Days ♻️ | Instant Start | Day 50K 🚀",
    price: 1.3066,
    oldPrice: 1.5679,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2888",
    network: "facebook",
    category: "Facebook Likes",
    title: "Facebook Post Likes [ Max 500K ] | HQ Accounts | Low Drop | 90 Days ♻️ | Instant Start | Day 50K 🚀",
    price: 1.3569,
    oldPrice: 1.6283,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2889",
    network: "facebook",
    category: "Facebook Likes",
    title: "Facebook Post Likes [ Max 500K ] | HQ Accounts | Low Drop | 365 Days ♻️ | Instant Start | Day 50K 🚀",
    price: 1.407,
    oldPrice: 1.6884,
    discount: 17,
    icon: "/icons/facebook.png",
  },

  // Facebook Members
  {
    id: "2664",
    network: "facebook",
    category: "Facebook Members",
    title: "Facebook Group Members [ Max 100K ] | HQ Accounts | Low Drop | No Refill ⚠️ | Fast | Day 50K 🚀",
    price: 2.7639,
    oldPrice: 3.3167,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2665",
    network: "facebook",
    category: "Facebook Members",
    title: "Facebook Group Members [ Max 100K ] | HQ Accounts | Low Drop | 30 Days ♻️ | Fast | Day 50K 🚀",
    price: 2.9147,
    oldPrice: 3.4976,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2666",
    network: "facebook",
    category: "Facebook Members",
    title: "Facebook Group Members [ Max 100K ] | HQ Accounts | Low Drop | 365 Days ♻️ | Fast | Day 50K 🚀",
    price: 3.0151,
    oldPrice: 3.6181,
    discount: 17,
    icon: "/icons/facebook.png",
  },

  // Facebook Reactions
  {
    id: "2895",
    network: "facebook",
    category: "Facebook Reactions",
    title: "Facebook Post Reaction [ Like 👍 ] [ Max 500K ] | No Refill ⚠️ | Day 10K",
    price: 0.367,
    oldPrice: 0.4404,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2896",
    network: "facebook",
    category: "Facebook Reactions",
    title: "Facebook Post Reaction [ Love ❤️ ] [ Max 500K ] | No Refill ⚠️ | Day 10K",
    price: 0.367,
    oldPrice: 0.4404,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2897",
    network: "facebook",
    category: "Facebook Reactions",
    title: "Facebook Post Reaction [ Care 🤗 ] [ Max 500K ] | No Refill ⚠️ | Day 10K",
    price: 0.367,
    oldPrice: 0.4404,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2898",
    network: "facebook",
    category: "Facebook Reactions",
    title: "Facebook Post Reaction [ Haha 😂 ] [ Max 500K ] | No Refill ⚠️ | Day 10K",
    price: 0.367,
    oldPrice: 0.4404,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2899",
    network: "facebook",
    category: "Facebook Reactions",
    title: "Facebook Post Reaction [ Wow 😲 ] [ Max 500K ] | No Refill ⚠️ | Day 10K",
    price: 0.367,
    oldPrice: 0.4404,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2900",
    network: "facebook",
    category: "Facebook Reactions",
    title: "Facebook Post Reaction [ Sad 😥 ] [ Max 500K ] | No Refill ⚠️ | Day 10K",
    price: 0.367,
    oldPrice: 0.4404,
    discount: 17,
    icon: "/icons/facebook.png",
  },
  {
    id: "2901",
    network: "facebook",
    category: "Facebook Reactions",
    title: "Facebook Post Reaction [ Angry 🤬 ] [ Max 500K ] | No Refill ⚠️ | Day 10K",
    price: 0.367,
    oldPrice: 0.4404,
    discount: 17,
    icon: "/icons/facebook.png",
  },

  // Twitch Followers
  {
    id: "2890",
    network: "twitch",
    category: "Twitch Followers",
    title: "Twitch Followers  [Max: 1M] [Start Time: Instant] [Speed: 300K/Day]",
    price: 1.5077,
    oldPrice: 1.8092,
    discount: 17,
    icon: "/icons/twitch.png",
  },
  {
    id: "2891",
    network: "twitch",
    category: "Twitch Followers",
    title: "Twitch Followers [ Max 10K ] | 30 Days Guaranteed ♻️ | Day 10K",
    price: 2.1106,
    oldPrice: 2.5327,
    discount: 17,
    icon: "/icons/twitch.png",
  },

  // Twitch Views
  {
    id: "2894",
    network: "twitch",
    category: "Twitch Views",
    title: "Twitch VOD Views [ Max 10M ] | 30 Days ♻️ | Day 2M",
    price: 0.4022,
    oldPrice: 0.4826,
    discount: 17,
    icon: "/icons/twitch.png",
  },

  // Kick Followers
  {
    id: "2902",
    network: "kick",
    category: "Kick Followers",
    title: "Kick Followers [ Max 50K ] | HQ | Non Drop | No Refill ⚠️ | Day 50K",
    price: 4.1209,
    oldPrice: 4.9451,
    discount: 17,
    icon: "/icons/kick.png",
  },
  {
    id: "2903",
    network: "kick",
    category: "Kick Followers",
    title: "Kick Followers [ Max 50K ] | HQ | Non Drop | 30 Days ♻️ | Day 50K",
    price: 4.3216,
    oldPrice: 5.1859,
    discount: 17,
    icon: "/icons/kick.png",
  },

  // Kick Views
  {
    id: "2904",
    network: "kick",
    category: "Kick Views",
    title: "Kick.com Live Stream Viewers [ Max 50K ] | 100% Stable | Drop 0% | 30 Minutes",
    price: 0.7036,
    oldPrice: 0.8443,
    discount: 17,
    icon: "/icons/kick.png",
  },
  {
    id: "2905",
    network: "kick",
    category: "Kick Views",
    title: "Kick.com Live Stream Viewers [ Max 50K ] | 100% Stable | Drop 0% | 60 Minutes",
    price: 1.407,
    oldPrice: 1.6884,
    discount: 17,
    icon: "/icons/kick.png",
  },
  {
    id: "2906",
    network: "kick",
    category: "Kick Views",
    title: "Kick.com Live Stream Viewers [ Max 50K ] | 100% Stable | Drop 0% | 120 Minutes",
    price: 2.8143,
    oldPrice: 3.3772,
    discount: 17,
    icon: "/icons/kick.png",
  },
  {
    id: "2907",
    network: "kick",
    category: "Kick Views",
    title: "Kick.com Live Stream Viewers [ Max 50K ] | 100% Stable | Drop 0% | 180 Minutes",
    price: 4.2212,
    oldPrice: 5.0654,
    discount: 17,
    icon: "/icons/kick.png",
  },

  // Spotify Followers
  {
    id: "2602",
    network: "spotify",
    category: "Spotify Followers",
    title: "Spotify Followers [Artist - Playlist] [1M/Day] [ Max 100M ]",
    price: 1.3869,
    oldPrice: 1.6643,
    discount: 17,
    icon: "/icons/spotify.png",
  },
  {
    id: "2795",
    network: "spotify",
    category: "Spotify Followers",
    title: "Spotify Followers [Artist - Playlist] [1M/Day] [ Max 100M ]",
    price: 1.3869,
    oldPrice: 1.6643,
    discount: 17,
    icon: "/icons/spotify.png",
  },
  {
    id: "2796",
    network: "spotify",
    category: "Spotify Followers",
    title: "Spotify Followers [Artist - Playlist] [1M/Day] [ Max 100M ]",
    price: 1.3869,
    oldPrice: 1.6643,
    discount: 17,
    icon: "/icons/spotify.png",
  },

  // Reddit Views
  {
    id: "2360",
    network: "reddit",
    category: "Reddit Views",
    title: "Reddit Views | 500M | Refill: 30 Days | ULTRAFAST | 0-10 Min | 100M/Day 🕵⚡♻️",
    price: 1.0051,
    oldPrice: 1.2061,
    discount: 17,
    icon: "/icons/reddit.png",
  },
  {
    id: "2362",
    network: "reddit",
    category: "Reddit Views",
    title: "Reddit Views + Shares | 500M | Refill: 30 Days | ULTRAFAST | 0-10 Min | 100M/Day 🕵⚡♻️",
    price: 2.0102,
    oldPrice: 2.4122,
    discount: 17,
    icon: "/icons/reddit.png",
  },

  // Reddit Shares
  {
    id: "2361",
    network: "reddit",
    category: "Reddit Shares",
    title: "Reddit Link Shares | 500M | Refill: 30 Days | Mid speed | 0-10 Min | 100M/Day 🕵⚡♻️",
    price: 1.0051,
    oldPrice: 1.2061,
    discount: 17,
    icon: "/icons/reddit.png",
  },

  // Snapchat Followers
  {
    id: "2675",
    network: "snapchat",
    category: "Snapchat Followers",
    title: "Snapchat Followers | Daily 500-1K | 100% Real Global | Max 10K | Slow",
    price: 45.2275,
    oldPrice: 54.273,
    discount: 17,
    icon: "/icons/snapchat.svg",
  },
  {
    id: "2674",
    network: "snapchat",
    category: "Snapchat Followers",
    title: "Snapchat Followers | Global Real Users | Max 10K | Slow",
    price: 72.4174,
    oldPrice: 86.9009,
    discount: 17,
    icon: "/icons/snapchat.svg",
  },

  // Snapchat Likes
  {
    id: "2586",
    network: "snapchat",
    category: "Snapchat Likes",
    title: "Snapchat Video Likes | Max 5K | No refill | Low Drop | UHQ | 1K-2K Day | Slow",
    price: 40.2022,
    oldPrice: 48.2426,
    discount: 17,
    icon: "/icons/snapchat.svg",
  },

  // Snapchat Other Services
  {
    id: "2585",
    network: "snapchat",
    category: "Snapchat Friend Requests",
    title: "Snapchat Friend Requests | Max 5K | No refill | Low Drop | UHQ | 1K-2K Day | Slow",
    price: 65.3286,
    oldPrice: 78.3943,
    discount: 17,
    icon: "/icons/snapchat.svg",
  },
{
  id: "2581",
  network: "snapchat",
  category: "Snapchat Snapscore Accounts !OPEN TICKET TO BUY!",
  title: "Snapchat Snapscore Accounts | 50k | No refill | UHQ | Slow",
  price: 3.00,
  icon: "/icons/snapchat.svg"
},
{
  id: "2585",
  network: "snapchat",
  category: "Snapchat Snapscore Accounts !OPEN TICKET TO BUY!",
  title: "Snapchat Snapscore Accounts | 100k | No refill | UHQ | Slow",
  price: 5.50,
  icon: "/icons/snapchat.svg"
},
{
  id: "2586",
  network: "snapchat",
  category: "Snapchat Snapscore Accounts !OPEN TICKET TO BUY!",
  title: "Snapchat Snapscore Accounts | 250k | No refill | UHQ | Slow",
  price: 12.00,
  icon: "/icons/snapchat.svg"
},
{
  id: "2587",
  network: "snapchat",
  category: "Snapchat Snapscore Accounts !OPEN TICKET TO BUY!",
  title: "Snapchat Snapscore Accounts | 500k | No refill | UHQ | Slow",
  price: 18.00,
  icon: "/icons/snapchat.svg"
},
{
  id: "2588",
  network: "snapchat",
  category: "Snapchat Snapscore Accounts !OPEN TICKET TO BUY!",
  title: "Snapchat Snapscore Accounts | 750k | No refill | UHQ | Slow",
  price: 23.00,
  icon: "/icons/snapchat.svg"
},
{
  id: "2589",
  network: "snapchat",
  category: "Snapchat Snapscore Accounts !OPEN TICKET TO BUY!",
  title: "Snapchat Snapscore Accounts | 1M | No refill | UHQ | Slow",
  price: 27.00,
  icon: "/icons/snapchat.svg"
},
{
  id: "2590",
  network: "snapchat",
  category: "Snapchat Snapscore Accounts !OPEN TICKET TO BUY!",
  title: "Snapchat Snapscore Accounts | 1.25M | No refill | UHQ | Slow",
  price: 29.00,
  icon: "/icons/snapchat.svg"
},
{
  id: "2591",
  network: "snapchat",
  category: "Snapchat Snapscore Accounts !OPEN TICKET TO BUY!",
  title: "Snapchat Snapscore Accounts | 1.5M | No refill | UHQ | Slow",
  price: 30.00,
  icon: "/icons/snapchat.svg"
}


  // WhatsApp Members
  {
    id: "2364",
    network: "whatsapp",
    category: "WhatsApp Members",
    title: "Whatsapp Channel Members [ Global 🌎 ] [ Max 50K ] | HQ Profiles | Day 10K",
    price: 7.5381,
    oldPrice: 9.0457,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2365",
    network: "whatsapp",
    category: "WhatsApp Members",
    title: "Whatsapp Channel Members [ Europe ] [ Max 50K ] | HQ Profiles | Day 20K",
    price: 15.0758,
    oldPrice: 18.091,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },

  // WhatsApp Reactions
  {
    id: "2501",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions | Random Mix [👍❤️😂😲😥🙏] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2502",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions [ 👍 ] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2503",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions [ ❤️ ] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2504",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions [ 😂 ] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2505",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions [ 😲 ] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2506",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions [ 😥 ] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2507",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions [ 🙏 ] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2508",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions [ 👏 ] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2509",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions [ 🔥 ] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2510",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions [ 🏆 ] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },
  {
    id: "2511",
    network: "whatsapp",
    category: "WhatsApp Reactions",
    title: "Whatsapp Channel Post Emoji Reactions [ 🎉 ] [ Max 50K ] | Instant Start",
    price: 3.769,
    oldPrice: 4.5228,
    discount: 17,
    icon: "/icons/whatsapp.png",
  },

  // Other Views
  {
    id: "2766",
    network: "Google",
    category: "Google Reviews",
    title: "Google Map Reviews [ Worldwide 🌏 ] [ Max 10K ] [ 5 Stars + Comments ] [ No Refill ⚠️ ] Slow",
    price: 2512.6424,
    oldPrice: 3015.1709,
    discount: 17,
    icon: "/icons/google.png",
  },
  {
    id: "2767",
    network: "Google",
    category: "Google Reviews",
    title: "Google Map Reviews [ Worldwide 🌏 ] [ Max 10K ] [ 5 Stars + Comments ] [ 30 Days ♻️ ] Slow",
    price: 3015.1709,
    oldPrice: 3618.2051,
    discount: 17,
    icon: "/icons/google.png",
  },
  {
    id: "2768",
    network: "Google",
    category: "Google Reviews",
    title: "Google Map Reviews [ Worldwide 🌏 ] [ Max 10K ] [ 5 Stars + Comments ] [ 365 Days ♻️ ] Slow",
    price: 3517.6994,
    oldPrice: 4221.2393,
    discount: 17,
    icon: "/icons/google.png",
  },

  // Other Other Services
  {
    id: "2921",
    network: "discord",
    category: "Discord Boosts",
    title: "Discord 14x Server Boost | 1 Month | Fast | UHQ",
    price: 17.46,
    oldPrice: 20.952,
    discount: 17,
    icon: "/icons/discord.jpeg",
  },
]

export const currencyRates: Record<string, number> = {
  EUR: 1,
  USD: 1.08,
  PLN: 4.35,
  GBP: 0.85,
  JPY: 169.0,
  CAD: 1.48,
  AUD: 1.64,
  CHF: 0.97,
  CNY: 7.83,
  INR: 90.0,
}
